### ISSUE TITLE
Suggestion: Keep dictionary keys in an enum

### ISSUE THREAD

**Issue by shebin-tw** [pavithran-mm/BullsEyeGame#1]
https://github.com/pavithran-mm/BullsEyeGame/blob/077e1fe93ad77c214af42dce04490fe42696f1de/BullsEye/Controllers/GameController.swift#L63

Suggestion: Keep dictionary keys in an enum, because it will avoid issues due to spelling mistakes & casing issues.

**Comment by pavithran-mm** [comment]
Yeah, Fixed
