### ISSUE TITLE
Good that you changed the swift file name. Suggesting to follow same for class name

### ISSUE THREAD

**Issue by shebin-tw** [pavithran-mm/BullsEyeGame#3]
https://github.com/pavithran-mm/BullsEyeGame/blob/077e1fe93ad77c214af42dce04490fe42696f1de/BullsEye/Views/GameViewController.swift#L10

Good that you changed the swift file name. Suggesting to follow same for class name

**Comment by pavithran-mm** [comment]
Oops! Missed that. Changed while fixing the Issue #1
