### ISSUE TITLE
Suggestion: Split the function further

### ISSUE THREAD

**Issue by shebin-tw** [pavithran-mm/BullsEyeGame#4]
https://github.com/pavithran-mm/BullsEyeGame/blob/077e1fe93ad77c214af42dce04490fe42696f1de/BullsEye/Views/GameViewController.swift#L38

You are doing multiple things in this function

* Update score
* Showing Alert
* startNewRound
* updateLabelsAndSlider

We can separate out the alert

**Comment by pavithran-mm** [comment]
Showing Alert moved to a separate function.
