### ISSUE TITLE
General Feedback on Codebase

### ISSUE THREAD

**Issue by shebin-tw** [pavithran-mm/BullsEyeGame#5]
Great job Pavithran. Good that you accommodated the following suggestion which we gave on 6th Sept 2022

* Created folders & moved files accordingly
* Moved the slider image setup into separate function https://github.com/pavithran-mm/BullsEyeGame/blob/077e1fe93ad77c214af42dce04490fe42696f1de/BullsEye/Views/GameViewController.swift#L64

**Happy to see that**
* you introduced a model class https://github.com/pavithran-mm/BullsEyeGame/blob/077e1fe93ad77c214af42dce04490fe42696f1de/BullsEye/Models/BullsEyeGame.swift#L11
* you are writing test cases. you are covering all business logics.
* the app is working seamlessly in iPhone 13 Pro Max
* you added meaningful app name & bundle id
* you added gitignore
* folder & file structure is good

Keep up the good work Pavithran

**Comment by pavithran-mm** [comment]
Thanks for the feedback, @shebin-tw !
